config/routes.rb
Rails.application.routes.draw do
  root "shifts#index"

  get "/login",  to: "sessions#new"
  post "/login", to: "sessions#create"
  get "/logout", to: "sessions#destroy"

  resources :users, only: [:show]
  resources :shifts, only: [:new, :create, :update]
end

app/models/shift.rb
class Shift < ActiveRecord::Base
  validates :date, :user_id, presence: true
  validate :date_cannot_be_in_the_past

  belongs_to :user

  def date_cannot_be_in_the_past
    errors.add(:date, "can't be in the past") if
      !date.blank? && date.to_date < Date.today
  end
end

app/models/shift_dates.rb
class ShiftDates
  def initialize(from)
    self.from = from[:from]
  end

  include Enumerable

  def each
    return to_enum :each unless block_given?
    current = from
    loop do
      yield current if shift?(current)
      current += 1
    end
  end

  private

  attr_accessor :from

  def shift?(date)
    weekday?(date) && !holiday?(date)
  end

  def holiday?(date)
    Holidays.on(date, :observed).any?
  end

  def weekday?(date)
    monday = 1
    friday = 5
    monday <= date.wday && date.wday <= friday
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  validates :name, presence: true
  has_many :shifts
  has_secure_password
  after_initialize :default_password

  def default_password
    self.password ||= "pw" if self.new_record?
  end

  enum role: %w(hero admin)
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  helper_method :todays_hero,
                :current_user,
                :current_user_is_hero,
                :current_user_is_admin,
                :select_id_from_available_user

  def todays_hero
    if todays_shift = Shift.find_by(date: Date.today)
      User.find_by(id: todays_shift.user_id).name
    end
  end

  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def current_user_is_hero
    current_user && current_user.hero?
  end

  def current_user_is_admin
    current_user && current_user.admin?
  end

  def all_users_except_current
    User.where("id not in (?)", current_user.id)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(name: params[:session][:name])
    if user && user.authenticate(params[:session][:password])
      flash[:success] = "Successfully logged in as #{user.name}"
      session[:user_id] = user.id
      redirect_to root_path
    else
      flash[:danger] = "Invalid Login"
      redirect_to :back
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:success] = "See you next time!"
    redirect_to root_path
  end
end

app/controllers/shifts_controller.rb
class ShiftsController < ApplicationController
  def index
    @shifts = Shift.all
  end

  def new
  end

  def create
    user_ids = map_input_by_user_id(params[:heroes])
    dates = ShiftDates.new(from: Date.today)
    user_ids.zip(dates).map { |id, date| Shift.create(date: date, user_id: id) }
    redirect_to root_path
  end

  def update
    if params[:commit] == "Swap!"
      shift = Shift.find(params[:id])
      shift.update_attributes(user_id: params[:shift][:user_id])
    else
      shift = Shift.find(params[:id])
      shift.update_attributes(user_id: all_users_except_current.sample.id)
    end

    flash[:success] = "Enjoy your day off!"
    redirect_to :back
  end

  private

  def map_input_by_user_id(sched)
    sched.scan(/\w+/).map { |name| User.find_or_create_by(name: name) }.map(&:id)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @shifts = Shift.where(user_id: current_user.id)
    @heroes = all_users_except_current
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li class="dropdown">
        <% if current_user %>
          <a href="#" class="dropdown-toggle brand" data-toggle="dropdown" role="button" aria-expanded="false">Welcome, <%= current_user.name %> <span class="caret"></span></a>
        <% else %>
          <a href="#" class="dropdown-toggle brand" data-toggle="dropdown" role="button" aria-expanded="false">Support Hero<span class="caret"></span></a>
        <% end %>
          <ul class="dropdown-menu" role="menu">
          <li><%= link_to "Home", root_path %></li>
            <% if current_user_is_hero %>
              <li class="divider"></li>
              <li><%= link_to "View My Shifts", user_path(current_user) %></li>
            <% elsif current_user_is_admin %>
              <li><%= link_to "Modify Schedule", new_shift_path %></li>
            <% end %>
          </ul>
        </li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
      <% if current_user %>
        <li class="active"><%= link_to "Logout", logout_path %></li>
      <% else %>
        <li class="active"><%= link_to "Login", login_path %></li>
      <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>SupportHero</title>
  <%= stylesheet_link_tag    "application", media: "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= render "layouts/navbar" %>

<div class="container">
  <% flash.each do |name, msg| %>
    <%= content_tag :div, msg, class: "alert alert-#{name} text-center" %>
  <% end %>
</div>

<%= yield %>

</body>
</html>

app/views/shifts/index.html.erb
<div clas="panel-body">
  <h1 align="center"> Welcome to Support Hero </h1>
  <h4 align="center"> Today's Date: <%= Date.today %> </h4>
  <br>
  <% if todays_hero %>
    <h3>Today's Scheduled Support Hero:</h3>
    <h4><pre><%= todays_hero %></pre></h4>
  <% end %>
</div>

<% if !@shifts.empty? %>
  <table class="table table-striped table-bordered">
  <caption class="text-center">Support Hero Schedule</caption>
    <thead>
      <tr>
        <th class="text-center">Date</th>
        <th class="text-center">Hero</th>
      </tr>
    </thead>
    <tbody>
      <% @shifts.each do |shift| %>
        <tr>
          <td class="text-center"><%= shift.date %></td>
          <td class="text-center"><%= shift.user.name %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
  <% else %>
    <h4 align="center"> There Are Currently No Scheduled Shifts </h4>
<% end %>

app/views/shifts/new.html.erb
<div class="container">
  <div class="row vertical-center-row">
    <div class="col-lg-12">
      <div class="row ">
        <div class="col-xs-4 col-xs-offset-4">
          <h2>Add Shifts</h2>
            <%= form_tag shifts_path(method: :post) do %>
              <%= text_area_tag(:heroes, nil, { size: "50x10" }) %>
              <%= submit_tag "Schedule!", class: "btn btn-success pull-right" %>
            <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div clas="panel-body">
  <h3 align="center"> Welcome <%= current_user.name %> </h1>
  <h4 align="center"> Today's Date: <%= Date.today %> </h4>
  <br>
</div>

<table class="table table-striped table-bordered">
<caption class="text-center">Your Upcoming Shifts</caption>
  <thead>
    <tr>
      <th class="text-center">Date</th>
      <th class="text-center">Mark Unavailable</th>
      <th class="text-center">Swap With Another User</th>
    </tr>
  </thead>
  <tbody>
    <% @shifts.each do |shift| %>
      <tr>
        <td class="text-center"><%= shift.date %></td>
        <td class="text-center">
          <%= form_tag shift_path(shift), method: :put do %>
            <%= submit_tag "Mark Unavailable", class: "btn-small btn-danger" %>
          <% end %>
        </td>
        <td class="text-center">
          <%= form_tag shift_path(shift), method: :put do %>
            <%= collection_select( :shift, :user_id, @heroes, :id, :name) %>
            <%= submit_tag "Swap!" %>
          <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>